/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNITest */

#ifndef _Included_JNITest
#define _Included_JNITest
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     JNITest
     * Method:    getMap
     * Signature: ()Ljava/util/HashMap;
     */
    JNIEXPORT jobject JNICALL Java_JNITest_getMap
    (JNIEnv* env, jclass obj);

#ifdef __cplusplus
}
#endif
#endif
