/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class newjni_JNITest */

#ifndef _Included_newjni_JNITest
#define _Included_newjni_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     newjni_JNITest
 * Method:    getMap
 * Signature: ()Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_newjni_JNITest_getMap
  (JNIEnv * env, jclass obj);

#ifdef __cplusplus
}
#endif
#endif
